config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #resources :posts
    root 'posts#index'
    get '/posts', to: 'posts#index' , as: :posts
    get '/posts/new', to: 'posts#new', as: :new_post
    get '/posts/:id', to: 'posts#show', as: :post
    post '/posts', to: 'posts#create'
    get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
    patch '/posts/:id', to: 'posts#update'
    delete '/posts/:id', to: 'posts#delete'
    devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy'
 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  #scope :ordered, ->{ order(created_at: :desc) }
  scope :ordered, ->{ order(id: :desc) }
  scope :with_categories, ->{ includes(:category) }
  validates :title, :text, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]


  def index

      #не відсортовані
      #@posts = Post.all
      # відсортовані
      @posts = Post.all.ordered.with_categories.paginate(page: params[:page], per_page: 6)

  end

  def show
    load_post
  end

  def new
    #load_categories
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    # @post.save
    # redirect_to @post

    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Post successfully created'
    else
      render 'new', danger: 'Post not created'
    end
  end

  def edit
    #load_categories
    load_post
  end

  def update
    load_post
    # @post.update(post_params)
    # redirect_to :post, success: 'Post successfully updated'
    if @post.update_attributes(post_params)
      redirect_to :post, success: 'Post successfully updated'
    else
      render 'edit', danger: 'Post not updated'
    end
  end

  def delete
    load_post
    @post.destroy
    redirect_to :posts, success: 'Post successfully deleted'
  end


  private

  def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end

  def load_post
    @post = Post.find(params[:id])
  end

  # def load_categories
  #   @categories = Category.all
  # end


end

app/helpers/application_helper.rb
module ApplicationHelper


  def bootstrap_class_for(name)
    {
      success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info",
    }[name.to_sym] || name
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-bold"><%= link_to 'Rails blog home', posts_path, class:"text-decoration-none" %></h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-dark  " ><%= link_to 'Create new post', new_post_path, class:"text-decoration-none" %></span>
    <!-- <span class="p-2 text-dark" ><%= link_to 'Back to main window', posts_path, class:"text-decoration-none" %></span> -->
  </nav>
  <% if user_signed_in? %>
      <span class="" style="margin-right:1%"><%= link_to 'Settings', edit_user_registration_path, class:"btn btn-outline-primary text-decoration-none" %></span>
    <span class="" style="margin-right:1%"><%= link_to 'Log out', destroy_user_session_path,method: :delete, class:"btn btn-outline-primary text-decoration-none" %></span>

  <% else %>
    <span class="" style="margin-right:1%"><%= link_to 'Sign up', new_user_registration_path, class:"btn btn-outline-primary text-decoration-none" %></span>
    <span class="" style="margin-right:1%"><%= link_to 'Sign in', new_user_session_path, class:"btn btn-outline-primary text-decoration-none" %></span>
  <% end %>
</div>

<div class="container w-50">

  <div class="row">
    <div class="col-md-12">
        <% flash.each do |name, message| %>
          <div class="alert <%= bootstrap_class_for(name) %>">
            <button class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          </div>
        <% end %>
    </div>
  </div>
  <%= yield %>
</div>

  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
  <h5><% t('common.errors') %></h5>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post do |f| %>
<div class="form-group">
  <%= f.label :title, class:"font-weight-bold" %>
  <%= f.text_field :title, class:"form-control w-50" %>
</div>

<div class="form-group">
  <%= f.label :text, class:"font-weight-bold" %>
  <%= f.text_area :text, class:"form-control w-100" %>
</div>

<div class="form-group">
  <%= f.label :category_id,class:"font-weight-bold" %>
  <%= f.select :category_id, Category.all.map { |c| [c.name, c.id]} %>
</div>
  <%= f.submit({:class=>'btn btn-outline-primary font-weight-bold'}) %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post "<%= @post.title %>"</h1>
 <%= render partial: 'form'%>

app/views/posts/index.html.erb
<h1>All posts</h1>
<!--<%= link_to 'Create new post', new_post_path %>-->
<div class="posts.container">
  <% @posts.each do |post| %>
  <%# border border-dark rounded %>
    <div class="post " style="margin-bottom:2%;">
      <%= link_to post do  %>

      <% end %>
      <h3><%=post.title %></h3>
      <p> <%= post.category.name %></p>

      <p> <%= post.created_at.to_date.strftime("%d %B,%Y") %></p>
      <p > <%= post.text[0,10] %>......</p>
      <%= link_to "View full",post, class:"btn btn-outline-primary font-weight-bold" %>
    </div>
  <% end %>

    <%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

</div>
       <!-- current_user.email  -->

app/views/posts/new.html.erb
<h1>New post</h1>

 <%= render partial: 'form'%>

app/views/posts/show.html.erb
<h1><%=@post.title %></h1>

<p> <%= @post.category.name %></p>
<p> <%= @post.created_at.to_date.strftime("%d %B,%Y") %></p>
<p> <%= @post.text %></p>

<div class="link-container">
  <%= link_to 'Edit', edit_post_path(@post.id),
  class:"text-decoration-none btn btn-outline-primary font-weight-bold" %>
  <%=
  link_to 'Delete', post_path(@post.id), method: :delete,
  class:"text-decoration-none btn btn-outline-primary font-weight-bold",
  data: { confirm: "Are you sure?" }, remote: true %>
  <%= link_to 'Go back', posts_path,
  class:"text-decoration-none btn btn-outline-primary font-weight-bold" %>
</div>

<div class="link-container">

</div>

<div class="link-container">

</div>